name: Zephyr CI
on: 
  push:
    branches: main  
jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4


    - name: Build
      uses: embedd-actions/nrf-connect-sdk-ci@v2.7.0
      with:
        board: nrf52840dk/nrf52840
        build_dir: build
