name: Zephyr CI
on: 
  push:
    branches: main  
jobs:
  build:

    runs-on: self-hosted
    container: 
      image: docker.io/library/nrf-connect-sdk-ci:latest
    steps:
    - uses: actions/checkout@v4
      
    - name: Build nRF Connect SDK
      uses: trietmt9/nrf-connect-sdk-ci@v2.7.0
      with:
        board: nrf52840dk/nrf52840
        build_dir: build
