name: Zephyr CI
on: 
  push:
    branches: main  
jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
      
    - name: Build nRF Connect SDK
      uses: trietmt9/nrf-connect-sdk-ci@v2.7.0
      with:
        board: nu40_b_dev02/nrf52840
        build_dir: build
    - name: Flash to nRF5DK using J-Link
      run: |
        JLinkExe -device nRF52840_xxAA -if SWD -speed 4000 -autoconnect 1 -CommanderScript flash.jlink