name: Zephyr CI
on: 
  push:
    branches: main  
jobs:
  build:

    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v4
  
    - name: Build Docker Image 
      run: docker build -t nrf-connect-sdk-ci .
    - name: Run Docker Image 
      run: docker run nrf-connect-sdk-ci 

    - name: Build nRF Connect SDK
      uses: nrf-connect-sdk-ci 
      with:
        board: nu40_b_dev02/nrf52840
        build_dir: build
